# Title of your homepage
title: FM Base Changelog 

# Website Description for search engines (optional)
description: "Keep yourself up to date with the latest FM Base changes"

# replace this word in navigation bar. Ex: Productnews, ChangeLog, Updates
heading: Updates

# absolute or relative path of logo
logo: https://i.imgur.com/s7IOBCg.png

# Your Product's Website
website: https://fm-base.co.uk

# the base hostname & protocol for your site, 
# e.g. https://updates.changelog.site
# Note Don't put trailing slash https://updates.changelog.site/
url: "https://changelog.fm-base.co.uk" 

baseurl: '' # optional


# Github username/repo where your code is hosted.
github: LiamPowers/changelog

# Global site tag (gtag.js) - Google Analytics e.g. UA-MYANALYTICS
analytics:  #(recommended)

# https://changelog-site.disqus.com
# disqus-identifier: changelog-site  # (optional)

# Allow users to comment via facebook
fb-comment: false

# Allow search engines to index your changelog website
allow-searchengine: true #optional


# Do not change anything below this if you don't know Jekyll

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets"
    values:
      sitemap: false 
  -
    scope:
      path: "admin"
    values:
      sitemap: false 

permalink: /:title/
markdown: kramdown
highlighter: rouge
sass:
  sass_dir:         _sass
  style:            compressed


plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap

pagination:
  enabled: true
  per_page: 5
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
